from BoursiereObj import Boursiere

b = Boursiere()
b.add_beer('Bush', 96, 1.9, 0.08, 0.05, 2.5)
b.add_beer('Orval', 96, 1.5, 0.08, 0.05, 2.5)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 5)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 7)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 5)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 10)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 2)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 0)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 3)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 4)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 0)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 0)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 14)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 20)
print(b.update_prices(do_round=True))
b.add_conso('Orval', 26)
print(b.update_prices(do_round=True))
b.to_json()
# raise Error because beer is out of stock

#b.add_conso('Orval', 27)
#print(b.update_prices(do_round=True))


#b.add_conso('Orval', 28)
#print(b.update_prices(do_round=True).to_json())
