# Generated by Django 2.2.3 on 2019-08-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('static_stock', models.IntegerField(default=100)),
                ('coef_up', models.FloatField()),
                ('coef_down', models.FloatField()),
                ('coef_max', models.FloatField()),
                ('q_qarder', models.IntegerField(default=0)),
                ('q_current_qarder', models.IntegerField(default=0)),
                ('alcohol_percentage', models.FloatField(default=0)),
                ('bar', models.IntegerField(default=1)),
                ('trend', models.CharField(default='EQUAL', max_length=10)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('best_value', models.BooleanField(default=False)),
                ('best_price', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('show_tool_bar', 'Can show the toolbar'), ('failsafe_mode', 'Can access to failsafe')),
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=25)),
                ('total_price', models.FloatField(default=0)),
                ('buy_total_price', models.FloatField(default=0)),
                ('history_json', models.TextField()),
                ('quarter', models.IntegerField(default=1)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_update', models.BigIntegerField()),
                ('timer_is_started', models.BooleanField(default=False)),
                ('current_quarter', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TresoFailsafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
    ]
