# Generated by Django 2.2.3 on 2019-07-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('coef_up', models.FloatField()),
                ('coef_down', models.FloatField()),
                ('coef_max', models.FloatField()),
                ('q_qarder', models.IntegerField()),
                ('q_current_qarder', models.IntegerField()),
                ('small_image', models.ImageField(upload_to='')),
                ('large_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
