# Generated by Django 2.2.3 on 2019-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='static_stock',
            field=models.IntegerField(),
        ),
    ]
