# Generated by Django 2.2.3 on 2019-07-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='large_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='small_image',
        ),
        migrations.AlterField(
            model_name='beer',
            name='q_current_qarder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beer',
            name='q_qarder',
            field=models.IntegerField(default=0),
        ),
    ]
