# Generated by Django 2.0 on 2019-09-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beer', '0002_auto_20190804_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='coef_min',
            field=models.FloatField(default=1.3),
            preserve_default=False,
        ),
    ]
