# Generated by Django 2.2.3 on 2019-07-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beer', '0002_auto_20190703_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=25)),
                ('time', models.TimeField()),
                ('history_json', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='beer',
            name='image',
        ),
    ]
