# Generated by Django 2.2.3 on 2019-07-05 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beer', '0003_auto_20190704_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='history',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
