# Generated by Django 2.2.3 on 2019-07-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beer', '0004_auto_20190705_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.CharField(max_length=25),
        ),
    ]
