# Generated by Django 2.2.3 on 2019-07-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beer', '0005_auto_20190705_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='alcohol_percentage',
            field=models.FloatField(default=0),
        ),
    ]
